apiVersion: v1
kind: Service
metadata:
  name: tourapp
spec:
  selector:
    app: tourapp
  type: LoadBalancer                      
  #  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 80
    #targetPort: 31755